### ISSUE TITLE
Regarding .apk file size increment after Integrating paypal card

### ISSUE THREAD

**Issue by krishnaxpertech** [card-io/card.io-Android-SDK#125]
Dear sir,
       I am developing an Android application previously(Paypal without "io.card") it size was 2.3 MB after integrating paypal io.card it increases its siz to 15 MB. I need both the payment options(Paypal Account & Card payment) but i don't want card scanning feature. So, please kindly let me know how to remove card scanning feature to reduce the size of .apk. Or any other way to reduce the size of .apk with both payment options.

I have read the discussion at link below, but i didn't found solution.
https://github.com/card-io/card.io-Android-SDK/issues/93

Thank you.

**Comment by romk1n** [comment]
@krishnaxpertech you just need to remove `.so` files from your package like described in this issue https://github.com/paypal/PayPal-Android-SDK/issues/226

**Comment by krishnaxpertech** [comment]
Thanks @romk1n  for your response, It is working now.
