### ISSUE TITLE
card expiry date 

### ISSUE THREAD

**Issue by Danielguang** [card-io/card.io-Android-SDK#167]
I used  card-io -cordova plugin,
but I cant get expiry date from my card.only card number info
, i have include the scanEpiry in my js files;
My card :Bank of China,
Color: grey
Card Type: MasterCard

**Comment by Danielguang** [comment]
Also test in Andorid Native, not supported

**Comment by Danielguang** [comment]
card.io  libaray :5.4.2

**Comment by netcleaner** [comment]
I also can't read the expiry date.
I used lastest version SDK. And set the setting like below.

scanIntent.putExtra(CardIOActivity.EXTRA_REQUIRE_EXPIRY, true);
scanIntent.putExtra(CardIOActivity.EXTRA_SCAN_EXPIRY, true);
scanIntent.putExtra(CardIOActivity.EXTRA_REQUIRE_CVV, false);
scanIntent.putExtra(CardIOActivity.EXTRA_REQUIRE_POSTAL_CODE, false); // default: false
scanIntent.putExtra(CardIOActivity.EXTRA_RESTRICT_POSTAL_CODE_TO_NUMERIC_ONLY, false);
scanIntent.putExtra(CardIOActivity.EXTRA_REQUIRE_CARDHOLDER_NAME, false);

**Comment by lkorth** [comment]
Duplicate of #119
