### ISSUE TITLE
card.io SampleApp camera scanning doesn't work on Nexus 5

### ISSUE THREAD

**Issue by MGhareeb32** [card-io/card.io-Android-SDK#168]
- Produced on card.io 5.3.0 and 5.4.2
- Device is Nexus 5

```
10-07 11:32:48.793 11714-11714/org.my.scanExample.debug I/card.io: Checking hardware support...
10-07 11:32:48.794 11714-11714/org.my.scanExample.debug I/card.io: card.io 5.4.2 09/27/2016 11:38:46 -0500
10-07 11:32:48.798 11714-11714/org.my.scanExample.debug E/card.io: Failed to load native library: dlopen failed: cannot locate symbol "__aeabi_memcpy" referenced by "/data/app/org.my.scanExample.debug-1/lib/arm/libcardioDecider.so"...
10-07 11:32:48.798 11714-11714/org.my.scanExample.debug W/card.io: - Processor type is not supported
```

**Comment by Alextorres950325** [comment]
10-10 13:36:46.930 8051-8051/com.foonkiemonkey.appservicios D/CardIOActivity: onDestroy()
10-10 13:39:48.010 8051-8051/com.foonkiemonkey.appservicios I/card.io: Checking hardware support...
10-10 13:39:48.010 8051-8051/com.foonkiemonkey.appservicios W/card.io: - Processor type is not supported
10-10 13:39:49.683 8051-8051/com.foonkiemonkey.appservicios I/CardIOActivity: onCreate()
10-10 13:39:49.685 8051-8051/com.foonkiemonkey.appservicios D/I18nManager: setLanguage(null)
10-10 13:39:49.685 8051-8051/com.foonkiemonkey.appservicios D/I18nManager: null not found.  Attempting to look for es_US
10-10 13:39:49.685 8051-8051/com.foonkiemonkey.appservicios D/I18nManager: setting locale to:es
10-10 13:39:49.686 8051-8051/com.foonkiemonkey.appservicios I/card.io: Processor not Supported. Skipping camera.
10-10 13:39:49.691 8051-8051/com.foonkiemonkey.appservicios I/CardIOActivity: onResume()

same problem in my case

**Comment by Alextorres950325** [comment]
W/card.io: - Processor type is not supported
10-10 13:39:49.683 8051-8051CardIOActivity: onCreate()
10-10 13:39:49.685 8051-8051 D/I18nManager: setLanguage(null)
10-10 13:39:49.685 8051-8051 D/I18nManager: null not found.  Attempting to look for es_US
10-10 13:39:49.685 8051-8051 D/I18nManager: setting locale to:es
10-10 13:39:49.686 8051-8051 I/card.io: Processor not Supported. Skipping camera.

**Comment by Alextorres950325** [comment]
After a long time searching, I compiled the version 5.4.0 and the problem was solved, This error appears in the following this verisones.

**Comment by paringer** [comment]
Huavey Honor 7
Samsung Galaxy J5 (SM-J500H)
same error with versions 5.4.1 - 5.4.2
10-17 12:45:34.843 1059-1059/com.tachcard E/card.io: Failed to load native library: dlopen failed: cannot locate symbol "__aeabi_memcpy" referenced by "/data/app/com.tachcard-1/lib/arm/libcardioDecider.so"...
10-17 12:45:34.843 1059-1059/com.tachcard I/card.io: Processor not Supported. Skipping camera.
after two hours of recompile, helps me only,
rolled back to version 5.4.0 and setting locale to english, after that, russion locale starts work too, 
scanIntent.putExtra(CardIOActivity.EXTRA_LANGUAGE_OR_LOCALE, "en");
so version is important, locale is not.
But unfortunately this version does not recognize my cards anymore. only new (unworkable at android) version 5.4.2 does at iOS

**Comment by qasimdm** [comment]
Skipping the camera activity:

Tried: 5.4.2, 5.4.1, 5.4.0 on Galaxy S5 (Marshmallow 6.0.1)
minSdkVersion 16

11-17 16:04:43.501 3023-3023/ I/CardIOActivity: onCreate()
11-17 16:04:43.511 3023-3023/ D/I18nManager: setLanguage(null)
11-17 16:04:43.511 3023-3023/ D/I18nManager: null not found.  Attempting to look for sv_SE
11-17 16:04:43.511 3023-3023/ D/I18nManager: setting locale to:sv
11-17 16:04:43.511 3023-3023/ I/card.io: Processor not Supported. Skipping camera.
11-17 16:04:43.511 3023-3023/ I/CardIOActivity: onResume()
11-17 16:04:43.511 3023-3023/ D/CardIOActivity: nextActivity()
