### ISSUE TITLE
card.io not working on marshmallow operating system device

### ISSUE THREAD

**Issue by abdulwaheed7989** [card-io/card.io-Android-SDK#170]
### Required Information
- card.io Android SDK Version: 5.4.2
- Android Version  (6.0 )and Device (Google nexus 5):
### Issue Description

> when I am launching for scanning it is not opening camera, i can see logs as below
>  E/card.io: Failed to load native library: dlopen failed: cannot locate symbol "__aeabi_memcpy" referenced by "/data/app/com.dd.cotech-2/lib/arm/libcardioDecider.so"...
>  I/card.io: Processor not Supported. Skipping camera.

Is there any any restriction on marshmallow

**Comment by lkorth** [comment]
There is no restriction on Marshmallow, this is an issue in the native code for certain versions of Android with specific processor architectures. See #166

**Comment by shah0664** [comment]
I am also facing the same issue:
Card IO SDK 5.4.2
Device: Honor 5x 
OS version Marshmellow

MinSDK version 16

It works fine on lollipop devices but in marshmellow device it opens manual entry for credit card.
