### ISSUE TITLE
Request for release 5.5.0 (with fix for S7 Edge)

### ISSUE THREAD

**Issue by artkow** [card-io/card.io-Android-SDK#176]
### Required Information
- card.io Android SDK Version: 5.4.2
- Android Version and Device: Samsung S7 Edge

### Issue Description
Actual version 5.4.2 doesn't work on devices like S7 Edge.
New merges fix this problem https://github.com/card-io/card.io-Android-source/pull/113

Could You release version with this changes, please.

**Comment by stief510** [comment]
+1

**Comment by lkorth** [comment]
Closed via ed89cf24ec3ecc57cd1903ec0b620a1673c10482
