### ISSUE TITLE
Card.io adds 13mb to apk size!

### ISSUE THREAD

**Issue by jeffkelsey** [card-io/card.io-Android-SDK#178]
### Required Information

- card.io Android SDK Version: 5.4.1
- Android Version: all

### Issue Description
Went through product testing and only realized drastic change to APK size just before release.  our production apk has gone from 18mb to > 30mb.   Verified with an empty project, with CardIO 13mb,  without cardIO 1.5mb.  This is madness, why so heavy?  GOING TO BE VERY HARD TO JUSTIFY THIS TO PRODUCT TEAM

**Comment by lkorth** [comment]
card.io includes [native code for each processor architecture](https://github.com/card-io/card.io-Android-source/tree/master/card.io/src/main/jni/lib) which results in a fairly sizable binary. Although it introduces some complexity to releases you can [split your apks](https://developer.android.com/studio/build/configure-apk-splits.html) to decrease the size for each architecture. Keep in mind that this is not the downloaded APK size or the installed size. 

Finally if you are not happy with the size of the library, there's nothing forcing you to use it.

**Comment by lkorth** [comment]
There are numerous other issues about this same topic: #88, #93 and #106.

**Comment by jeffkelsey** [comment]
We work with native libraries that have to support multiple architectures and apk splitting, but others are not nearly this large. I assume by closing the issue this means that card.io is not planning to work on reducing these sizes in the future, which is problematic, but will be useful information in making  a decision. Thanks for the answers.
