### ISSUE TITLE
license error

### ISSUE THREAD

**Issue by kvr1995** [card-io/card.io-Android-SDK#183]
Error:Gradle: A problem occurred configuring root project 'SampleApp'.
> You have not accepted the license agreements of the following SDK components:
[Android SDK Build-Tools 25, Android SDK Platform 25].
Before building your project, you need to accept the license agreements and complete the installation of the missing components using the Android Studio SDK Manager.
Alternatively, to learn how to transfer the license agreements from one workstation to another, go to http://d.android.com/r/studio-ui/export-licenses.html

**Comment by lkorth** [comment]
You have not accepted the new license version on your computer, you must do this before the gradle build plugin will automatically download any dependencies it needs. This is not part of card.io, but the Android gradle build plugin.
