### ISSUE TITLE
Remove Paypal Logo in DataEntry

### ISSUE THREAD

**Issue by DevPicon** [card-io/card.io-Android-SDK#200]
How could I remove the paypal logo in DataEntryActivity for manual card number entries?

**Comment by lkorth** [comment]
See the [extras](https://github.com/card-io/card.io-Android-source/blob/d97905f8003be5266ecc2bd444c0cc82add05d60/card.io/src/main/java/io/card/payment/CardIOActivity.java#L214) that can be supplied when starting the scanning `Activity`. There are a few different options for the logos that are displayed.
