### ISSUE TITLE
Invoking card.io library in Android App pushes the app to background

### ISSUE THREAD

**Issue by ravikanthmarri** [card-io/card.io-Android-SDK#202]
### General information

* io.card:android-sdk:5.5.1
* Android Version : 6.0.1 and Sony Xperia Z3 D6603

### Issue description

When the camera is launched from card.io, our App is pushed to background.
For the security reasons we have to lock the app if it is moved to background.
So by the time card.io is finished and called onActivityResult , our app is brought to foreground but its on the password screen.

The requirement does not allow us to keep the app unlocked when its pushed to background.

This problem does not happen in card.io iOS SDK.

Is there any way to invoke card.io camera with-in our app so that it does not go to background ?

**Comment by Kdaydin** [comment]
Don't know if its possible but you can try to convert CardIOActivity to fragment.

**Comment by kpprasanth** [comment]
Same problem occurs for me, i have tried to detect the onpause() and onResume() but it doesn't work. Is there any solution for this ?

**Comment by kpprasanth** [comment]
Hey, did u got any solution for this?

**Comment by lkorth** [comment]
card.io is running within your app, however it is an `Activity` and only 1 `Activity` is active at a time in an app.

You'd either have to convert card.io to a custom view or `Fragment`, or change the logic in your app for when it displays a password prompt.

See card-io/card.io-Android-source#53
