### ISSUE TITLE
No option to remove flash icon

### ISSUE THREAD

**Issue by scorpeeon** [card-io/card.io-Android-SDK#205]
Using the latest version (5.5.1).

There are many flags to customize how this component works but found no flag to remove the flash toggle icon from the UI. Wouldn't it make sense to have that as well?
(possibly with another flag to force turn on the flash by default)

**Comment by lkorth** [comment]
There are currently no plans to add this, but if you'd like to submit a PR to https://github.com/card-io/card.io-Android-source we can review and merge it.
