### ISSUE TITLE
Privacy Risk 

### ISSUE THREAD

**Issue by sahir** [card-io/card.io-Android-SDK#220]
We are using card.io library in one of our application and Norton anti-virus app is throwing the below-attached error. Could you please let us know the reason behind this privacy risk and are we sharing any sort of information outside the application.

<img width="330" alt="screen shot 2018-01-31 at 11 26 34 am" src="https://user-images.githubusercontent.com/452706/35675495-3b89235e-076e-11e8-96f1-76baedb39283.png">

**Comment by bluk** [comment]
Which version of card.io is your app using? The open source version of card.io in this repository should not send any information back to PayPal. The open source version's code is located at https://github.com/card-io/card.io-Android-source . I suggest using the open source version if this is a concern.

**Comment by lkorth** [comment]
Which version of card.io is this? Recent versions of it [don't even have Internet or Phone permissions](https://github.com/card-io/card.io-Android-source/blob/ce20888144b60708278531af3144eff414c2ff02/card.io/src/main/AndroidManifest.xml).
