### ISSUE TITLE
Question: Recognition name holder

### ISSUE THREAD

**Issue by oruam85** [card-io/card.io-Android-SDK#45]
Hi, great sdk!!. Do you plan to include recognition of name holder?

**Comment by dgoldman-ebay** [comment]
Thanks for the feedback, @oruam85 !

Right now we're working on scanning the expiration date. It's a tricky challenge!

Once that's done, we'd love to look into scanning the card holder's name. But that would be even trickier, so no promises at this time.

**Comment by ayeshdon** [comment]
some this return expiration date and some time not.why
