### ISSUE TITLE
Problems with cards recognize

### ISSUE THREAD

**Issue by IP696** [card-io/card.io-Android-SDK#46]
We are using card.io library in our project. And we have problems with it. The credit cards recognized very slowly and uncorrectly. Example:
1. We using this example card: http://trademark.ua/wp-content/uploads/2013/03/torgovaya-marka-visa.jpg 
   On Android and iOS devices this card recognized in 10-15 seconds and some digits recognized wrong (7 as 2 and 8 as 6). 
2. We using this example card: http://www.creditcardchaser.com/wp-content/uploads/2010/11/nyu-credit-card.jpg 
    and it's not recognized.
3. We using real credit cards - first is green with black digits, and second is grey with black digits. Android example from GitHub isn't recognized it, but iOS example app reconized it in 1-2 minutes, but some digits are wrong.
We change lighting in the ofice, use different cards positions, but no one card is recognized correctly.

**Comment by dgoldman-ebay** [comment]
@IP696 thanks for your report. We definitely appreciate you taking the time to experiment with card positions and lighting conditions.

For cases 1 and 2, are you using the actual images, on a computer display, from the URLs shown? If so, then I'm actually delighted that card.io is doing as well as you describe -- it was never designed to work with such artificial images!

For case 3,  are these American Express cards? We do often find that card.io has difficulties with many American Express cards (especially the ones with dark digits over a green background).

**Comment by tomwhipple** [comment]
I'm going to close this, as I'm not sure we can really take much action to address this specific issue. In general, computer vision is hard so we will never get it right 100% of the time. That said, we do occasionally make improvements that may make a difference, but we won't be able to know if this specific case has been addressed.
