### ISSUE TITLE
Missing cancel button

### ISSUE THREAD

**Issue by theneverstill** [card-io/card.io-Android-SDK#6]
If I setup card.io with the following parameters, I arrive at an interesting problem: the lack of an escape/cancel button (the first 2 parameters may be all that matter).

scanIntent.putExtra(CardIOActivity.EXTRA_SUPPRESS_CONFIRMATION, true);
scanIntent.putExtra(CardIOActivity.EXTRA_SUPPRESS_MANUAL_ENTRY, true);
scanIntent.putExtra(CardIOActivity.EXTRA_REQUIRE_EXPIRY, false);
scanIntent.putExtra(CardIOActivity.EXTRA_REQUIRE_CVV, false);
scanIntent.putExtra(CardIOActivity.EXTRA_REQUIRE_POSTAL_CODE, false);

At this point I am forced to make a card scan happen or I must use the native android back button. I assume since iOS doesn't have a native back button then one must have been added to that code base. Would it be possible make a back button optional on android? (Target audience would be devices in kiosk mode that have had the hardware buttons disabled and soft keys hidden.)

**Comment by tomwhipple** [comment]
It doesn't look like we will be able to prioritize this, as the kiosk case is not typical. However, given that this project is now open source, we will consider pull requests.
