### ISSUE TITLE
No detecting any kind of credit card

### ISSUE THREAD

**Issue by julen30** [card-io/card.io-Android-SDK#70]
The camera appears but the credit card is never recognized. I focus the card inside the square but never takes the information automatically and stays there forever.

**Comment by NammariMarkavip** [comment]
I got the same behavior  too

**Comment by tomwhipple** [comment]
card.io is designed to work with standard fixed width embossed card numbers that are typical in North America. Even then, some cards are more difficult to read than others and success will vary depending upon the card, lighting conditions and device camera.
