### ISSUE TITLE
Supported Devices

### ISSUE THREAD

**Issue by longtagdevelopment** [card-io/card.io-Android-SDK#71]
I just purchased an Apzen Tablet Device to use with card.io, only to realize that only back camera is supported. Just returning it now while I bought a different device to find out that the tablet's camera resolution is too low. 

Does anyone have a working list of tablets (or any specific recommendations)? I've been filtering by A7 (arm7) processors so far. Does anyone know if an a9 processor, which is newer and easier to come by, will also work?

Thank you

**Comment by tomwhipple** [comment]
Card scanning requires ARMv7a or better. ARM64 architectures should work, though you might have to build [from source](https://github.com/card-io/card.io-Android-source) yourself.

(We intent to update the binary build soon.)
