### ISSUE TITLE
Android CardIOActivity - default scanning screen cutomization

### ISSUE THREAD

**Issue by nishamaria** [card-io/card.io-Android-SDK#72]
Hi,
Is it possible to customize the default scanning screen? 
From https://github.com/card-io/card.io-Android-SDK/issues/40 I notice that we cannot add buttons, text field etc.. to the default scanning screen. Is this still the case with version 5.0.1?

Also, is it possible to customize the Keyboard button and modify the text. Can I pass in a custom text which gets displayed instead of "Keyboard" on the default scanner activity?

**Comment by tomwhipple** [comment]
Yes.

The card.io is [open source](https://github.com/card-io/card.io-Android-source)!
