### ISSUE TITLE
Possible to default to manual entry

### ISSUE THREAD

**Issue by marchinram** [card-io/card.io-Android-SDK#73]
Is there an extra to pass to the CardIOActivity that will default it to manual keyboard entry with the option to use the camera?

**Comment by tomwhipple** [comment]
No. 

However, you're welcome to modify the [source](https://github.com/card-io/card.io-Android-source) yourself if you desire such a feature.

**Comment by marchinram** [comment]
Created pr for this: https://github.com/card-io/card.io-Android-source/pull/25
