### ISSUE TITLE
Xamarin card.io component fails to scan using camera in Release mode

### ISSUE THREAD

**Issue by chatterjb** [card-io/card.io-Android-SDK#74]
I suspect this is due to a linking issue with Xamarin.Android, but I am never able to use the camera to scan a card specifically in Release mode. Works fine in debug mode. When I check the device logs, this is what I see:

07-28 22:03:01.878 E/card.io ( 5582): Failed to load native library: JNI_ERR returned from JNI_OnLoad in "/data/app/kwpAndroid.kwpAndroid-1/lib/arm/libcardioRecognizer.so" 07-28 22:03:01.878 W/card.io ( 5582): - Processor type is not supported 07-28 22:03:01.878 W/card.io ( 5582): ERROR_NO_DEVICE_SUPPORT: This device cannot use the camera to read card numbers.

Based on other posts for native Android, this apparently happens when the native libraries are not in the project's '/libs' directory. But how do I get this to work in Xamarin.Android?

**Comment by tomwhipple** [comment]
Unfortunately Xamarin is not supported by the card.io team. 

However, now that card.io is open source, we would consider any relevant pull requests to the [Android source repo](https://github.com/card-io/card.io-Android-source).
