### ISSUE TITLE
Zip code change input

### ISSUE THREAD

**Issue by PGMacDesign** [card-io/card.io-Android-SDK#75]
Hey guys, first off, exceptional job with this library, huge props!

Quick enhancement, with regards to zip code entry when this extra is enabled:
scanIntent.putExtra(CardIOActivity.EXTRA_REQUIRE_POSTAL_CODE, true);

You get to the screen where you enter in the zip code and it switches to letters instead of numbers for the edit text.
Would it make sense to change the input method on the zip code edit text to:
android:inputType="number"    
Or is that something done intentionally due to other places using this may have something other than numbers in their zip codes?

**Comment by agustingandara** [comment]
Its generic, there are alphanumeric zip codes, https://en.wikipedia.org/wiki/List_of_postal_codes

**Comment by PGMacDesign** [comment]
Understood, ty for clarifying.
