### ISSUE TITLE
Remove Paypal logo

### ISSUE THREAD

**Issue by root1** [card-io/card.io-Android-SDK#77]
How do i remove the Paypal logo when the camera is opened

**Comment by agustingandara** [comment]
Intent scanIntent = new Intent(MainActivity.this, CardIOActivity.class);
scanIntent.putExtra(CardIOActivity.EXTRA_HIDE_CARDIO_LOGO, true); // default: false
scanIntent.putExtra(CardIOActivity.EXTRA_USE_PAYPAL_ACTIONBAR_ICON, false); // default: true

**Comment by root1** [comment]
Ok Thanks pal

**Comment by serkansekman** [comment]
Thansk @agustingandara
